# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20180323_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user_id',
            new_name='user',
        ),
    ]
